// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping.Models;

namespace OnlineShopping.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("OnlineShopping.Models.Entity.Dil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.ToTable("Dil");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "French"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Japonca"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Lazca"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.Oyun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cikis_tarihi");

                    b.Property<int>("FirmaID")
                        .HasColumnType("int")
                        .HasColumnName("firma_id");

                    b.Property<int>("Fiyat")
                        .HasColumnType("int")
                        .HasColumnName("fiyat");

                    b.Property<int>("PlatformID")
                        .HasColumnType("int")
                        .HasColumnName("platform_id");

                    b.HasKey("Id");

                    b.HasIndex("FirmaID");

                    b.HasIndex("PlatformID");

                    b.ToTable("Oyun");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Fifa 2021",
                            CikisTarihi = new DateTime(2021, 5, 15, 2, 48, 52, 650, DateTimeKind.Local).AddTicks(9501),
                            FirmaID = 1,
                            Fiyat = 1,
                            PlatformID = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Last Of Us",
                            CikisTarihi = new DateTime(2021, 5, 15, 2, 48, 52, 652, DateTimeKind.Local).AddTicks(1121),
                            FirmaID = 2,
                            Fiyat = 100,
                            PlatformID = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Cyberpunk 2088",
                            CikisTarihi = new DateTime(2021, 5, 15, 2, 48, 52, 652, DateTimeKind.Local).AddTicks(1180),
                            FirmaID = 3,
                            Fiyat = 55,
                            PlatformID = 2
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Euro Drug Simulator",
                            CikisTarihi = new DateTime(2021, 5, 15, 2, 48, 52, 652, DateTimeKind.Local).AddTicks(1183),
                            FirmaID = 1,
                            Fiyat = 85,
                            PlatformID = 1
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Football Manager 2023",
                            CikisTarihi = new DateTime(2021, 5, 15, 2, 48, 52, 652, DateTimeKind.Local).AddTicks(1184),
                            FirmaID = 1,
                            Fiyat = 200,
                            PlatformID = 3
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.OyunDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DilID")
                        .HasColumnType("int")
                        .HasColumnName("dil_id");

                    b.Property<int>("OyunID")
                        .HasColumnType("int")
                        .HasColumnName("oyun_id");

                    b.HasKey("Id");

                    b.HasIndex("DilID");

                    b.HasIndex("OyunID");

                    b.ToTable("OyunDil");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DilID = 2,
                            OyunID = 1
                        },
                        new
                        {
                            Id = 2,
                            DilID = 3,
                            OyunID = 2
                        },
                        new
                        {
                            Id = 3,
                            DilID = 3,
                            OyunID = 1
                        },
                        new
                        {
                            Id = 4,
                            DilID = 1,
                            OyunID = 4
                        },
                        new
                        {
                            Id = 5,
                            DilID = 4,
                            OyunID = 3
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.OyunTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("OyunID")
                        .HasColumnType("int")
                        .HasColumnName("oyun_id");

                    b.Property<int>("TagID")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("OyunID");

                    b.HasIndex("TagID");

                    b.ToTable("OyunTag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OyunID = 1,
                            TagID = 2
                        },
                        new
                        {
                            Id = 2,
                            OyunID = 2,
                            TagID = 3
                        },
                        new
                        {
                            Id = 3,
                            OyunID = 1,
                            TagID = 3
                        },
                        new
                        {
                            Id = 4,
                            OyunID = 4,
                            TagID = 1
                        },
                        new
                        {
                            Id = 5,
                            OyunID = 3,
                            TagID = 4
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.ToTable("Platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Windows"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Linux"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "MacOS"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ad");

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Co-Op"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Single"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Multi"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Grind"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Ad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Ulke")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ulke");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("Firma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ubisoft",
                            Ulke = "Azerbaycan",
                            Website = "www.cum.zone"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Erzurum Game Studios",
                            Ulke = "Türkiye",
                            Website = "www.erzu.rum"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Rockstar",
                            Ulke = "Erzincan",
                            Website = "www.rock.star"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.Oyun", b =>
                {
                    b.HasOne("OnlineShopping.Models.Firma", "FirmaFK")
                        .WithMany()
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Entity.Platform", "PlatformFK")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirmaFK");

                    b.Navigation("PlatformFK");
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.OyunDil", b =>
                {
                    b.HasOne("OnlineShopping.Models.Entity.Tag", "DilFK")
                        .WithMany()
                        .HasForeignKey("DilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Entity.Oyun", "OyunFK")
                        .WithMany()
                        .HasForeignKey("OyunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DilFK");

                    b.Navigation("OyunFK");
                });

            modelBuilder.Entity("OnlineShopping.Models.Entity.OyunTag", b =>
                {
                    b.HasOne("OnlineShopping.Models.Entity.Oyun", "OyunFK")
                        .WithMany()
                        .HasForeignKey("OyunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Entity.Tag", "TagFK")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OyunFK");

                    b.Navigation("TagFK");
                });
#pragma warning restore 612, 618
        }
    }
}
